# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-13 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20170508_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='live',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(auto_now_add=True, verbose_name=b'date created')),
                ('sound', models.IntegerField()),
                ('wifi', models.IntegerField()),
            ],
        ),
    ]
