# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-13 13:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20170513_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='crowdedness',
            name='name',
            field=models.CharField(default=datetime.datetime(2017, 5, 13, 13, 50, 34, 126268, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crowdedness',
            name='type',
            field=models.CharField(default=datetime.datetime(2017, 5, 13, 13, 50, 42, 311102, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
